import { BudgetItem } from './types';

export const BUDGET_DATA: BudgetItem[] = [
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "1 MATERIAL DE EXPEDIENTE", id: "1.1.1.1", value: 7725.10 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "2 MATERIAL DE LIMPEZA E OUTROS", id: "1.1.1.2", value: 12836.76 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "3 MATERIAL DE HIGIENE PESSOAL", id: "1.1.1.3", value: 14396.22 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "4 MATERIAL PARA OFICINA DE PANIFICAÇÃO", id: "1.1.1.4", value: 6823.11 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "5 MATERIAL ESPORTIVO", id: "1.1.1.5", value: 4297.00 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "6 MATERIAL PARA VESTUÁRIO, UNIFORMES, CAMA, MESA, BANHO E AFINS", id: "1.1.1.6", value: 29549.60 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "7 MATERIAL PARA MANUTENÇÃO DE BENS MÓVEIS E IMÓVEIS", id: "1.1.1.7", value: 11950.00 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "8 MATERIAL PARA INFRAESTRUTURA DE TECNOLOGIA DA INFORMAÇÃO", id: "1.1.1.8", value: 15000.00 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "9 MATERIAL PARA OFICINA OLEICULTURA", id: "1.1.1.9", value: 3452.10 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "10 SERVIÇO DE MANUTENÇÃO DE BENS MÓVEIS E IMÓVEIS", id: "2.1.2.10", value: 9600.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "11 SERVIÇO DE FORNECIMENTO DE ALIMENTOS", id: "2.1.2.11", value: 552277.44 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "12 SERVIÇO DE LOCAÇÃO DE VEÍCULOS", id: "2.1.2.12", value: 144000.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "13 SERVIÇOS DE SEGURANÇA DO TRABALHO E SISTEMA PREVENTIVO DE COMBATE A INCÊNDIO", id: "2.1.2.13", value: 48000.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "14 SERVIÇOS DE SAÚDE", id: "2.1.2.14", value: 6000.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "15 SERVIÇO DE VIDEOMONITORAMENTO POR CÂMERAS", id: "2.1.2.15", value: 211654.80 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "16 SERVIÇOS DE MANUTENÇÃO DE TECNOLOGIA DA INFORMAÇÃO", id: "2.1.2.16", value: 57000.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "17 SERVIÇO DE VIGILÂNCIA ARMADA", id: "2.1.2.17", value: 162000.00 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "18 SERVIÇO EMBALAGEM E TRANSPORTE DE MÓVEIS", id: "2.1.2.18", value: 65000.00 },
  { stage: "1. Implantação de Unidade Socioeducativa (30 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "19 SERVIÇO INSTALAÇÃO E MANUTENÇÃO DE AR CONDICIONADO", id: "2.1.2.19", value: 20000.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "20 SERVIÇOS ADMINISTRATIVOS INDIRETOS", id: "2.1.2.20", value: 123156.96 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "21 COMBUSTÍVEIS E LUBRIFICANTES", id: "2.1.1.21", value: 186009.96 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "3. Diárias e Passagens", type: "3. Diárias e Passagens", desc: "22 DIÁRIAS E ESTADIAS", id: "2.1.3.22", value: 8499.60 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "23 ENERGIA ELÉTRICA", id: "2.1.2.22", value: 81000.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "1. Material de Consumo", type: "1. Material de Consumo", desc: "24 FORNECIMENTO DE MEDICAMENTOS E INSUMOS DE ENFERMAGEM", id: "2.1.2.24", value: 16800.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "1. Custeio", category: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", type: "2. Prestação de Serviços de Terceiros Pessoa Jurídica", desc: "25 SERVIÇOS DE TELECOMUNICAÇÃO", id: "2.1.2.25", value: 12000.00 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "2. Pessoal e Encargos Sociais", category: "4. Vencimentos e Salários", type: "4. Vencimentos e Salários", desc: "26 PAGAMENTO DE SALÁRIOS", id: "2.2.4.26", value: 2035625.09 },
  { stage: "2. Manutenção da Gestão Socioeducativa (180 dias)", group: "2. Pessoal e Encargos Sociais", category: "5. Encargos Sociais e Provisões", type: "5. Encargos Sociais e Provisões", desc: "27 ENCARGOS E PROVISÕES", id: "2.2.5.27", value: 734634.48 }
];

export const STORAGE_KEY = 'ledger_pt_022026_v5_3';
export const AUDIT_STORAGE_KEY = 'ledger_pt_022026_v5_3_audit';
